#!/bin/bash

MOUNT_POINT=/cupy-vol

if [[ "$1" == *".py" ]]
then
  file=$(basename $1)

  CMD="python3 ${MOUNT_POINT}/$1"
  MOUNT="--volume $PWD:${MOUNT_POINT}:Z"

  shift
else
  file="cupy-0"
  echo file=${file}
  CMD=""
  MOUNT="--volume $PWD:${MOUNT_POINT}:Z"
fi

#CMD="ls -alh ${MOUNT_POINT}"
CMD="${CMD} $@"

# $(timedatectl show -p Timezone --value) these values do not work in the cupy/cupy image

# change the default below to suit your needs or set the TZ variable before running this script.
TZ=${TZ:-PST8PDT}

# Don't do this - Needs to run as root to write to /.cupy
# --user ${UID}:${UID}

# Updated to run on bluefin-dx-nvidia-open:stable
RUN_CMD="podman \
  run \
  --security-opt=no-new-privileges \
  --cap-drop=ALL \
  --security-opt label=type:nvidia_container_t  \
  --device=nvidia.com/gpu=all \
  ${MOUNT} \
  -e TZ=${TZ} --name ${file} --rm -it \
  cupy/cupy \
  ${CMD}"

echo ${RUN_CMD}
${RUN_CMD}

# This was working on Fedora WS 40
# echo podman run ${MOUNT} --device nvidia.com/gpu=all -e TZ=${TZ} --name ${file} --rm -it cupy/cupy ${CMD}
# podman run ${MOUNT} --device nvidia.com/gpu=all -e TZ=${TZ} --name ${file} --rm -it cupy/cupy ${CMD}

# This was working on Fedora WS 40 - after --gpus=all flag was added
# echo podman run ${MOUNT} --gpus=all -e TZ=${TZ} --name ${file} --rm -it cupy/cupy ${CMD}
# podman run ${MOUNT} --gpus=all -e TZ=${TZ} --name ${file} --rm -it cupy/cupy ${CMD}
